// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function StopProcess(arg1) {
  return window['go']['main']['Launcher']['StopProcess'](arg1);
}

export function WatchOutput(arg1) {
  return window['go']['main']['Launcher']['WatchOutput'](arg1);
}
