// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function StopProcess(arg1:string):Promise<boolean>;

export function WatchOutput(arg1:string):Promise<any>;
